version: '3.8'
services:
    tides-react:
        container_name: tides-react
        build:
            context: .
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - 3000:3000

